sudo: required
  
# Enable C++ support
language: cpp
dist: trusty

# Compiler selection
compiler:
  - g++
 
matrix:
  include:
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"



before_install:
  # Install gcc 7 && autotool
  - apt list --installed | grep g++
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update -qq
  - g++-7 -v --verbose 
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - /sbin/ldconfig -p | grep stdc++

# Build steps
script:
  - g++-7 -Wl,--rpath /usr/lib/gcc/x86_64-linux-gnu/7.3.0/ -std=c++1z ./test.cpp -v --verbose
  #- ./configure 
    #- autoreconf -if
    #- make -j4
    #- make regression

