sudo: required
  
# Enable C++ support
language: cpp


# Compiler selection
compiler:
  - g++
 
matrix:
  include:
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env:
      - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"



before_install:
  # Install gcc 7 && autotool
  - apt list --installed | grep g++
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install libstdc++6
  - g++-8 -v --verbose
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
  - /sbin/ldconfig -p | grep stdc++

# Build steps
script:
  - g++-8 -std=c++1z ./test.cpp -v --verbose
  #- ./configure 
    #- autoreconf -if
    #- make -j4
    #- make regression

