sudo: required
  
# Enable C++ support
language: cpp


# Compiler selection
compiler:
  - g++
 
matrix:
  include:
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"



before_install:
  # Install gcc 7 && autotool
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install libstdc++6
  - g++-7 -v
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - /sbin/ldconfig -p | grep stdc++

# Build steps
script:
  - g++-7 -std=c++17 ./test.cpp
  #- ./configure 
    #- autoreconf -if
    #- make -j4
    #- make regression

